# SPDX-License-Identifier: MIT

- name: Find environment-specific tasks to enable repositories
  set_fact:
    __gfs2_enable_repo_tasks_file: \
      "{{ __gfs2_enable_repo_tasks_file_candidate }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - >-
      {{ ansible_facts['distribution'] ~ '_' ~
      ansible_facts['distribution_major_version'] }}.yml
    - >-
      {{ ansible_facts['distribution'] ~ '_' ~
      ansible_facts['distribution_version'] }}.yml
  vars:
    __gfs2_enable_repo_tasks_file_candidate: \
      "{{ role_path }}/tasks/enable-repositories/{{ item }}"
  when:
    - gfs2_enable_repos
    - __gfs2_enable_repo_tasks_file_candidate is file

- name: Run environment-specific tasks to enable repositories
  include_tasks: "{{ __gfs2_enable_repo_tasks_file }}"
  when:
    - gfs2_enable_repos
    - __gfs2_enable_repo_tasks_file is defined

- name: Install packages
  ansible.builtin.package:
    name: "{{ __gfs2_packages }}"
    state: present
  become: true
  any_errors_fatal: true
